language: python
python:
  - "3.5"
addons:
  apt:
    update: true
before_install:
  - sudo apt-get install -y virtualbox
install:
  - pip install -r requirements-dev.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - pytest --cov-config .coveragerc --cov=linuxiso tests
after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
