general:
  dir_input: ""       # <directory where offical iso are>
  dir_isocustom: "" # <directory to put custom iso>
  dir_build: ""     # <temp directory where we build iso>

download :
  debian-9.6.0-strech-amd64-netinst.iso:
    label: Debian 9.6.0 Strech amd64 Netinst
    url_iso: https://cdimage.debian.org/debian-cd/9.6.0/amd64/iso-cd/debian-9.6.0-amd64-netinst.iso
    hash:
      type: sha1
      sum: fe23b2849fe417081d3e4424f0cb8a4dd00d3a8e

custom:
  iso:
    myhostname2.iso: # <Unique iso name>
      receipt: Custom-FullAuto-Debian-9-strech-amd64-netinst-server-raid # Receipts listed in linux/custom/receipts
      vars:
        hostname: myhostname2         # <Unique hostnamename>
        domain: example.lan           # <Domaine name>
        var_ntp_server: pool.ntp.org  # <NTP serveur> for time synchronisation
        root_password: mypassword     # <root password>
        user_name: myuser             # <user name>
        user_password: mypassword     # <user password>

virtualbox:
  vms :
    myhostname2:      # <Vm name>
      install: myhostname2.iso   # <iso install>
      os_type : 'Debian_64'     # Id fourni dans la liste : VBoxManage list ostypes |egrep '^ID:'|awk '{print $2}'
      file_disk_type : 'wlan0'   # vdi | vmdk
      ram : 1024              # multiple de x^2 : exemple 1*1024
      vram : 128              # mémoire video
      disk_size : [32768,32768]       # multiple de x^2 : exemple 8*1024

      interface_name: ''      # Votre interface de connection externe donnée par /sbin/ifconfig
      interface_type: 'bridged'    # bridged | ...
