
geeral:
  dir_input: ""       # <directory where offical iso are>
  dir_isocustom: "" # <directory to put custom iso>
  dir_build: ""     # <temp directory where we build iso>

custom:
  contexts:
    uniquehostname: # <Unique hostnamename>
      hostname: myhostname
      domain: example.lan           # <Domaine name>
      var_ntp_server: pool.ntp.org  # <NTP serveur> for time synchronisation
      root_password: mypassword     # <root password>
      user_name: myuser             # <user name>
      user_password: mypassword     # <user password>

      # Optional : Add user ansible for automatic deployed
      # option_ansible:
      #   ansible_user_name: ansible
      #   ansible_authorized_keys:
      #   - ssh-rsa xxxxxxxxxxxxxxxxxxxxxx
      # Optional : Add HTTP POST each time the OS start.
      #  The body contain the "ansible host status"
      # option_post_start_running:
      #   url: localhost             # <url HTTP POST serveur>
      #   port: 9001                 # <port HTTP POST serveur>

virtualbox:
  recipes :
    Debian-amd64-raid:
      #hostname: 'test debian'
      os_type : 'Debian_64'     # Id fourni dans la liste : VBoxManage list ostypes |egrep '^ID:'|awk '{print $2}'
      file_disk_type : 'wlan0'   # vdi | vmdk
      ram : 1024              # multiple de x^2 : exemple 1*1024
      vram : 128              # mémoire video
      disk_size : [32768,32768]       # multiple de x^2 : exemple 8*1024

      interface_name: 'wlan0'      # Votre interface de connection externe donnée par /sbin/ifconfig
      interface_type: 'bridged'    # bridged | ...
